package com.urlshortner.domain;

import java.time.Instant;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * URL row persisted in MySQL. The primary key is generated by MySQL {@code AUTO_INCREMENT}
 * (see the V1 schema) — the application no longer allocates ids itself, since the shortCode is
 * derived deterministically from the URL via MurmurHash3, not from the id.
 *
 * <p>No setters are exposed: the entity is write-once at the application layer. Post-construction
 * mutation is limited to Hibernate's reflective population on load and the scheduled click flush,
 * which increments {@code total_clicks} directly through {@code JdbcTemplate}.
 */
@Entity
@Table(name = "urls")
public class UrlEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", columnDefinition = "BIGINT UNSIGNED")
    private Long id;

    @Column(name = "short_code", nullable = false, unique = true, length = 32,
            columnDefinition = "VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin")
    private String shortCode;

    @Column(name = "original_url", nullable = false, length = 2048)
    private String originalUrl;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "expires_at")
    private Instant expiresAt;

    @Column(name = "total_clicks", nullable = false,
            columnDefinition = "BIGINT UNSIGNED NOT NULL DEFAULT 0")
    private long totalClicks;

    protected UrlEntity() {
    }

    public UrlEntity(String shortCode, String originalUrl, Instant expiresAt) {
        this.shortCode = shortCode;
        this.originalUrl = originalUrl;
        this.expiresAt = expiresAt;
    }

    @PrePersist
    void onCreate() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
    }

    public Long getId() {
        return id;
    }

    public String getShortCode() {
        return shortCode;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public long getTotalClicks() {
        return totalClicks;
    }

    /**
     * Identity by primary key. Two transient entities (both {@code id == null}) are never equal —
     * consistent with JPA best practice, which forbids using un-persisted entities as map keys.
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (!(other instanceof UrlEntity that)) return false;
        return this.id != null && this.id.equals(that.id);
    }

    @Override
    public int hashCode() {
        // Stable across the entity's lifecycle: use the class hash, not id.hashCode(), so that
        // transient (id == null) → persistent (id assigned) doesn't shift the bucket in a Set.
        return UrlEntity.class.hashCode();
    }
}
